#
#  _____       _                 _____                  _
# |  __ \     | |               / ____|                | |
# | |  | | ___| |_   ___  _____| |     ___  _   _ _ __ | |_ ___ _ __
# | |  | |/ _ \ | | | \ \/ / _ \ |    / _ \| | | | '_ \| __/ _ \ '__|
# | |__| |  __/ | |_| |>  <  __/ |___| (_) | |_| | | | | ||  __/ |
# |_____/ \___|_|\__,_/_/\_\___|\_____\___/ \__,_|_| |_|\__\___|_|
#
#
# Author: FusionCoding
# Version: 1.0
# State: ALPHA
#
General:
 Prefix: "&bDeluxe&7Counter \xbb &7"
