name: DeluxeCounter
version: 1.0
main: de.fusion.deluxecounter.DeluxeCounter
author: FusionCoding
description: A lightweight BungeeCord plugin to monitor the connections per second.
website: https://deluxenode.com/
database: false
commands:
  deluxecounter:
    aliases: [dc, counter]